import { transactionStatus, transactionType } from "./schemas/transaction_schema";

export const sampleTransactions = [
  {
    senderAccountNumber: '1234567890',
    recipientAccountNumber: '0987654321',
    recipientAccountName: 'Jide Ilugbo',
    amount: 50,
    transactionType: transactionType.DEBIT,
    tansactionStatus: transactionStatus.PENDING,
    description: 'Sample transaction 1',
  },
  {
    senderAccountNumber: '2234567890',
    recipientAccountNumber: '1987654321',
    recipientAccountName: 'Jane Smith',
    amount: 100,
    transactionType: transactionType.CREDIT,
    tansactionStatus: transactionStatus.SUCCESSFUL,
    description: 'Sample transaction 2',
  },
  {
    senderAccountNumber: '3234567890',
    recipientAccountNumber: '2987654321',
    recipientAccountName: 'Alice Inaka',
    amount: 75,
    transactionType: transactionType.DEBIT,
    tansactionStatus: transactionStatus.FAILED,
    description: 'Sample transaction 3',
  },
  {
    senderAccountNumber: '4234567890',
    recipientAccountNumber: '3987654321',
    recipientAccountName: 'Ansu Fati',
    amount: 200,
    transactionType: transactionType.CREDIT,
    tansactionStatus: transactionStatus.PENDING,
    description: 'Sample transaction 4',
  },
  {
    senderAccountNumber: '5234567890',
    recipientAccountNumber: '4987654321',
    recipientAccountName: 'Majemu Adewale',
    amount: 400,
    transactionType: transactionType.DEBIT,
    tansactionStatus: transactionStatus.SUCCESSFUL,
    description: 'Sample transaction 5',
  },
  {
    senderAccountNumber: '4234567890',
    recipientAccountNumber: '3987654321',
    recipientAccountName: 'Ansu Fati',
    amount: 700,
    transactionType: transactionType.CREDIT,
    tansactionStatus: transactionStatus.PENDING,
    description: 'Sample transaction 6',
  },
  {
    senderAccountNumber: '5234567890',
    recipientAccountNumber: '4987654321',
    recipientAccountName: 'Majemu Adewale',
    amount: 500,
    transactionType: transactionType.DEBIT,
    tansactionStatus: transactionStatus.SUCCESSFUL,
    description: 'Sample transaction 7',
  },
  {
    senderAccountNumber: '2234567890',
    recipientAccountNumber: '1987654321',
    recipientAccountName: 'Jane Smith',
    amount: 800,
    transactionType: transactionType.CREDIT,
    tansactionStatus: transactionStatus.SUCCESSFUL,
    description: 'Sample transaction 8',
  },
];
